export { default } from "next-auth/middleware";

export const config = {
  matcher: [
    "/",
    "/uploadpage",
    "/profile",
    "/downloadpage",
    "/waitingpage",
    "/pricing",
    "/seo_keywords",
    "/taxonomy",
    "/enhancementPage",
    "/how-to-guide",
    "/walmart/dashboard",
    "/walmart/enhancements",
    "/walmart/generate",
    "/walmart/pricing",
    "/walmart/results",
    "/walmart/sync",
    "/walmart/feeds",
    "/dashboard/products",
    "/dashboard/documents",
    "/dashboard/activity",
    "/dashboard/enhancements",
    "/dashboard/home",
    "/dashboard/how-to-guide",
    "/dashboard/img_rec_download",
    "/dashboard/pricing",
    "/dashboard/profile",
    "/dashboard/settings/management",
    "/dashboard/settings/compliance",
  ],
};
